name: Ruff
on:
  pull_request:
    branches:
      - main
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"
      - run: ruff check --fix
      - run: ruff format